name: your name
description: your description
url: http://domain.com
domain: domain.com

source:      .
destination: ./_site
plugins:     ./_plugins

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000

pygments:    false
permalink:   /:title/