name: your name
description: your description
url: http://domain.com
domain: domain.com

source:      .
destination: ./_build
plugins:     ./_plugins

host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000

pygments:    false
permalink:   /:title/