# Rakefile
# Author: Vitor Britto
# Version: 1.0.0
# Made with Ruby, Coffee and Love. :)

task default: [:watch]

task :build do
  build_sass
  # build_coffeescript
  # build_javascript
  # build_template
end

task :watch do
    build_sass
    # build_coffeescript
    # build_javascript
    # build_template
    pids = [
        # spawn("coffee -w"),
        # spawn("uglify command here"),
        # spawn("haml command here"),
        spawn("compass watch")
    ]

    trap "INT" do
        Process.kill "INT", *pids
        exit 1
    end

    pids.each do |pid|
        Process.wait pid
    end

    # loop do
    #     sleep 1
    # end
end

def build_sass
  system("compass compile")
end

# def build_coffeescript
#   system("coffee -co ../public/assets/js ../assets/coffee")
# end

# def build_javascript
#   system("")
# end

# def build_template
#   system("")
# end

